spring:
  application:
    name: llm-spring-ai

  ai:
    openai:
      api-key: sk-ws-H.EPIYIDM.v6Gz.MEUCIQDcFl2bqaq1Zp_B_iw7UlSuD6SRH0HNQXe8-LRoO79_gwIgJMQ2Rbnr22HPhPRokEAldsugpW1G881arKu3VIYxXe8
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen3.7-plus
      embedding:
        base-url: https://dashscope.aliyuncs.com/compatible-mode
        api-key: sk-ws-H.EPIYIDM.v6Gz.MEUCIQDcFl2bqaq1Zp_B_iw7UlSuD6SRH0HNQXe8-LRoO79_gwIgJMQ2Rbnr22HPhPRokEAldsugpW1G881arKu3VIYxXe8
        options:
          model: text-embedding-v4
          dimensions: 768
    vectorstore:
      pgvector:
        index-type: HNSW              # HNSW = 分层可导航小世界图，检索快但多占内存
        distance-type: COSINE_DISTANCE # 余弦距离，比方向不比长度，适合文本语义
        dimensions: 768                # 向量维度，必须和 embedding 模型输出一致
        max-document-batch-size: 10    # 每次往库里批量写几条（受 embedding 模型限制）
        initialize-schema: true        # 首次启动自动建表，跑通后改 false
        table-name: vector_store       # 表名随便起

  datasource:
    url: jdbc:postgresql://localhost:5433/rag_test
    username: pgvector
    password: 123456

server:
  port: 8081
